Disable openjdk10 in travis bc. of travis bug
* What went wrong:
Could not resolve all files for configuration ':pmd'.
> Could not resolve net.sourceforge.pmd:pmd-java:6.9.0.
  Required by:
      project :
   > Could not resolve net.sourceforge.pmd:pmd-java:6.9.0.
      > Could not parse POM https://jcenter.bintray.com/net/sourceforge/pmd/pmd-java/6.9.0/pmd-java-6.9.0.pom
         > Could not resolve net.sourceforge.pmd:pmd:6.9.0.
            > Could not resolve net.sourceforge.pmd:pmd:6.9.0.
               > Could not get resource 'https://jcenter.bintray.com/net/sourceforge/pmd/pmd/6.9.0/pmd-6.9.0.pom'.
                  > Could not GET 'https://jcenter.bintray.com/net/sourceforge/pmd/pmd/6.9.0/pmd-6.9.0.pom'.
                     > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target